package com.msaidizi.app.core.dialect

import com.msaidizi.app.core.model.DialectRegion

/**
 * Data-driven configuration for Migori County Swahili dialect adapter.
 *
 * Migori Swahili has heavy Luo (Dholuo) substrate influence:
 * - Dholuo-Swahili code-switching at clause boundaries
 * - Luo vocabulary borrowed into Swahili context
 * - Phonological transfer: implosive consonants bleed into Swahili
 */
object MigoriDialectData {

    val config = DialectConfig(
        name = "Migori",
        languageCode = "sw",
        region = DialectRegion.MIGORI,

        markers = mapOf(
            "kendo" to Regex("\\bkendo\\b"),
            "to" to Regex("\\bto\\b"),
            "ka" to Regex("\\bka\\b"),
            "mano" to Regex("\\bmano\\b"),
            "gi" to Regex("\\bgi\\b"),
            "nyiso" to Regex("\\bnyiso\\b"),
            "en" to Regex("\\ben\\b"),
            "ok" to Regex("\\bok\\b"),
            "kata" to Regex("\\bkata\\b"),
            "chon" to Regex("\\bchon\\b"),
            "nadi" to Regex("\\bnadi\\b"),
            "inyalo" to Regex("\\binyalo\\b"),
            "kia" to Regex("\\bkia\\b"),
            "ber" to Regex("\\bber\\b"),
            "maber" to Regex("\\bmaber\\b"),
            "malo" to Regex("\\bmalo\\b"),
            "yawuoyo" to Regex("\\byawuoyo\\b"),
            "amos" to Regex("\\bamos\\b"),
            "erokamano" to Regex("\\berokamano\\b"),
            "chuthi" to Regex("\\bchuthi\\b"),
            "dhok" to Regex("\\bdhok\\b"),
            "ogo" to Regex("\\bogo\\b"),
            "wuon" to Regex("\\bwuon\\b"),
            "min" to Regex("\\bmin\\b"),
            "ja" to Regex("\\bja\\b"),
            "juak" to Regex("\\bjuak\\b"),
            "tich" to Regex("\\btich\\b"),
            "paro" to Regex("\\bparo\\b"),
            "saa" to Regex("\\bsaa\\b"),
            "pod" to Regex("\\bpod\\b"),
            "piny" to Regex("\\bpiny\\b"),
            "piyo" to Regex("\\bpiyo\\b"),
            "rech" to Regex("\\brech\\b"),
            "uong'" to Regex("\\buong'\\b"),
            "rimo" to Regex("\\brimo\\b"),
            "are" to Regex("\\bare\\b"),
            "ng'ato" to Regex("\\bng'ato\\b"),
            "moko" to Regex("\\bmoko\\b"),
            "oduol" to Regex("\\boduol\\b"),
            "ng'wen" to Regex("\\bng'wen\\b"),
            "siru" to Regex("\\bsiru\\b"),
            "pesa" to Regex("\\bpesa\\b"),
            "ot" to Regex("\\bot\\b"),
            "daraja" to Regex("\\bdaraja\\b")
        ),

        pronunciationRegexes = mapOf(
            "samini" to Regex("\\bsamini\\b", RegexOption.IGNORE_CASE),
            "sababu" to Regex("\\bsababu\\b", RegexOption.IGNORE_CASE),
            "sulu" to Regex("\\bsulu\\b", RegexOption.IGNORE_CASE),
            "sahabu" to Regex("\\bsahabu\\b", RegexOption.IGNORE_CASE),
            "aka" to Regex("\\baka\\b", RegexOption.IGNORE_CASE),
            "apata" to Regex("\\bapata\\b", RegexOption.IGNORE_CASE),
            "oka" to Regex("\\boka\\b", RegexOption.IGNORE_CASE),
            "iga" to Regex("\\biga\\b", RegexOption.IGNORE_CASE),
            "osha" to Regex("\\bosha\\b", RegexOption.IGNORE_CASE),
            "naani" to Regex("\\bnaani\\b", RegexOption.IGNORE_CASE),
            "saafi" to Regex("\\bsaafi\\b", RegexOption.IGNORE_CASE),
            "twaa" to Regex("\\btwaa\\b", RegexOption.IGNORE_CASE),
            "pesa" to Regex("\\bpesa\\b", RegexOption.IGNORE_CASE),
            "rejareja" to Regex("\\brejareja\\b", RegexOption.IGNORE_CASE),
            "mboga" to Regex("\\bmboga\\b", RegexOption.IGNORE_CASE),
            "ng'ombe" to Regex("\\bng'ombe\\b", RegexOption.IGNORE_CASE)
        ),

        pronunciationVariations = mapOf(
            "samini" to "thamini",
            "sababu" to "thababu",
            "sulu" to "thuru",
            "sahabu" to "thahabu",
            "aka" to "taka",
            "apata" to "tapata",
            "oka" to "toka",
            "iga" to "piga",
            "osha" to "tosha",
            "naani" to "nani",
            "saafi" to "safi",
            "twaa" to "twa",
            "pesa" to "pesa",
            "rejareja" to "rejareja",
            "mboga" to "mboga",
            "ng'ombe" to "ng'ombe"
        ),

        dialectMarkerWords = setOf(
            "kendo", "to", "ka", "mano", "gi", "nyiso", "en", "ok",
            "kata", "chon", "nadi", "inyalo", "kia", "ber", "maber",
            "malo", "yawuoyo", "amos", "erokamano", "chuthi", "dhok",
            "ogo", "wuon", "min", "ja", "juak", "tich", "paro",
            "saa", "pod", "piny", "piyo", "rech", "uong'", "rimo",
            "are", "ng'ato", "moko", "oduol", "ng'wen", "siru", "ot", "daraja"
        ),

        businessTerms = mapOf(
            "omena" to "omena",
            "omena kubwa" to "omena_kubwa",
            "rech" to "food",
            "piyo" to "groundnuts",
            "kuon" to "ugali",
            "atapa" to "atapa",
            "ugali sima" to "ugali_sima",
            "nyoyo" to "nyoyo",
            "odo" to "odo",
            "apoth" to "traditional_greens",
            "ng'wen" to "debt",
            "debe" to "debe",
            "debe_ndogo" to "debe_small",
            "debe_kubwa" to "debe_large",
            "gunia" to "gunia",
            "gunia_ndogo" to "gunia_small",
            "fundo" to "fundo",
            "mfuko" to "mfuko",
            "kibuyu" to "kibuyu",
            "goro" to "goro",
            "kibaba" to "kibaba",
            "ratili" to "ratili",
            "mbao" to "mbao",
            "jeuri" to "jeuri",
            "kibabu" to "kibabu",
            "ngiri" to "ngiri",
            "thao" to "thao",
            "finje" to "finje",
            "nane" to "nane",
            "jioni" to "jioni",
            "mali" to "goods",
            "mpakani" to "border",
            "shepu" to "clearing",
            "forodha" to "customs",
            "mugongo" to "back_load",
            "soko" to "market",
            "duka" to "shop",
            "kibanda" to "stall",
            "mama_mboga" to "mama_mboga",
            "mzee_wa_duka" to "shopkeeper",
            "boda_boda" to "boda_boda",
            "mkokoteni" to "mkokoteni",
            "gari_la_mizigo" to "cargo_vehicle",
            "chuthi" to "market_day",
            "ja_kuma" to "fish_trader",
            "ja_rech" to "food_vendor",
            "wuon_duka" to "shop_owner",
            "min_mboga" to "vegetable_mama",
            "ng'ombe" to "cattle",
            "mbuzi" to "goat",
            "kondoo" to "sheep",
            "kuku" to "chicken",
            "ng'ina" to "hen",
            "dier" to "bull"
        ),

        dialectToSwahili = mapOf(
            "kendo" to "na",
            "to" to "kisha",
            "ka" to "kama",
            "gi" to "na",
            "ok" to "si",
            "kata" to "hata",
            "chon" to "kwa sababu",
            "nadi" to "sasa",
            "ber" to "nzuri",
            "maber" to "nzuri",
            "malo" to "asante",
            "erokamano" to "asante sana",
            "amos" to "tafadhali",
            "rech" to "chakula",
            "piyo" to "njugu",
            "kuon" to "ugali",
            "ogo" to "nyumbani",
            "wuon" to "mmiliki",
            "ng'wen" to "deni",
            "siru" to "mkopo",
            "ot" to "duka"
        )
    )
}
