// ============================================================
// Msaidizi Android App — build.gradle.kts
// ============================================================
// Uses KSP (not kapt) for annotation processing.
// Kotlin 2.0.21, KSP 2.0.21-1.0.28, Hilt 2.52, Room 2.6.1
// Requires: NDK r26b, CMake 3.22.1
// ============================================================

import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")  // replaces: id("org.jetbrains.kotlin.kapt")
    id("com.google.dagger.hilt.android")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("io.gitlab.arturbosch.detekt")
}

detekt {
    config.setFrom("$rootDir/config/detekt/detekt.yml")
    buildUponDefaultConfig = true
    allRules = false
    disableDefaultRuleSets = false
    ignoredBuildTypes = listOf("debug")

    reports {
        html.required.set(true)
        xml.required.set(true)
        sarif.required.set(false)
        txt.required.set(false)
    }
}

android {
    namespace = "com.msaidizi.app"
    compileSdk = 35

    ndkVersion = "26.1.10909125"  // NDK r26b — stable with AGP 8.2.x

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    defaultConfig {
        applicationId = "com.msaidizi.app"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            // Support both 64-bit (arm64-v8a) and 32-bit (armeabi-v7a) ARM devices.
            // Many devices in Africa are still 32-bit (Tecno, Infinix, Itel budget phones).
            // 32-bit devices run in cloud-only mode — native llama.cpp models are too large
            // for their limited RAM (≤2GB usable). See DeviceCapability.is32BitDevice().
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }

        // Build config fields for model paths
        buildConfigField("String", "MODEL_DIR", "\"models\"")
        buildConfigField("String", "WHISPER_MODEL", "\"ggml-tiny.en-q5_1.bin\"")
        // Decision Council (2026-07-15): Qwen 3.5 0.8B as primary LLM
        buildConfigField("String", "LLM_MODEL", "\"Qwen3.5-0.8B-Q4_K_M.gguf\"")
        // Decision Council (2026-07-15): Gemma 4 E2B as alternative/benchmark LLM
        buildConfigField("String", "LLM_MODEL_ALT", "\"gemma-4-e2b-Q4_K_M.gguf\"")
        buildConfigField("String", "TTS_MODEL", "\"piper-swahili.onnx\"")
        buildConfigField("String", "VAD_MODEL", "\"silero_vad.onnx\"")

        // Sentry crash reporting DSN (set via environment or local.properties)
        val sentryDsn = project.findProperty("SENTRY_DSN") as? String ?: ""
        buildConfigField("String", "SENTRY_DSN", "\"${sentryDsn}\"")
    }

    // ============================================================
    // Signing Configuration
    // ============================================================
    // Debug: auto-generates a keystore if none exists (CI-friendly)
    // Release: reads from keystore.properties OR env vars (CI-friendly)
    //
    // To sign release builds locally:
    //   1. Run: ./scripts/generate-keystore.sh
    //   2. Fill in keystore.properties with your passwords
    //   3. Build: ./gradlew assembleRelease
    //
    // To sign in CI (GitHub Actions):
    //   Set these repository secrets:
    //     RELEASE_KEYSTORE_BASE64  — base64-encoded .keystore file
    //     RELEASE_STORE_PASSWORD   — keystore password
    //     RELEASE_KEY_ALIAS        — key alias name
    //     RELEASE_KEY_PASSWORD     — key password
    // ============================================================
    signingConfigs {
        getByName("debug") {
            // Use project-local debug.keystore if present, otherwise fall back to
            // ~/.android/debug.keystore (auto-generated by Android SDK)
            val localDebugKeystore = file("${rootProject.projectDir}/debug.keystore")
            if (localDebugKeystore.exists()) {
                storeFile = localDebugKeystore
            } else {
                storeFile = file("${System.getProperty("user.home")}/.android/debug.keystore")
            }
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        create("release") {
            // PKCS12 (.p12) or JKS keystore — auto-detected from file extension
            // CI: set RELEASE_KEYSTORE_BASE64 secret (base64-encoded .p12 file)
            // Local: create keystore.properties with storeFile entry
            val envStoreFile = System.getenv("RELEASE_KEYSTORE_FILE")
            val envStorePassword = System.getenv("RELEASE_STORE_PASSWORD")
            val envKeyAlias = System.getenv("RELEASE_KEY_ALIAS")
            val envKeyPassword = System.getenv("RELEASE_KEY_PASSWORD")

            if (!envStoreFile.isNullOrBlank() && !envStorePassword.isNullOrBlank()) {
                val ksFile = File(envStoreFile)
                val resolvedFile = if (ksFile.isAbsolute) ksFile else file("${rootProject.projectDir}/$envStoreFile")
                if (resolvedFile.exists()) {
                    storeFile = resolvedFile
                    storePassword = envStorePassword
                    keyAlias = envKeyAlias ?: "msaidizi-release"
                    keyPassword = envKeyPassword ?: envStorePassword
                    // Auto-detect store type from file extension
                    storeType = if (storeFile?.name?.endsWith(".p12", true) == true) "pkcs12" else "jks"
                } else {
                    // Env var set but file missing — fall back to debug
                    println("WARNING: RELEASE_KEYSTORE_FILE=$envStoreFile does not exist, falling back to debug signing")
                    val projectDebugKs = file("${rootProject.projectDir}/debug.keystore")
                    val homeDebugKs = file("${System.getProperty("user.home")}/.android/debug.keystore")
                    val fallbackKs = if (projectDebugKs.exists()) projectDebugKs else homeDebugKs
                    storeFile = fallbackKs
                    storePassword = "android"
                    keyAlias = "androiddebugkey"
                    keyPassword = "android"
                }
            } else {
                val props = Properties()
                val propsFile = file("${rootProject.projectDir}/keystore.properties")
                if (propsFile.exists()) {
                    props.load(propsFile.inputStream())
                }
                val propsStoreFile = props.getProperty("storeFile", "")
                if (propsStoreFile.isNotBlank()) {
                    // Custom release keystore defined in keystore.properties
                    storeFile = file(propsStoreFile)
                    storePassword = props.getProperty("storePassword", "")
                    keyAlias = props.getProperty("keyAlias", "msaidizi-release")
                    keyPassword = props.getProperty("keyPassword", "")
                    // Auto-detect store type from file extension (PKCS12 vs JKS)
                    storeType = if (storeFile?.name?.endsWith(".p12", true) == true) "pkcs12" else "jks"
                } else {
                    // No custom release keystore — fall back to debug keystore
                    // Check project-local debug.keystore first (CI generates this),
                    // then ~/.android/debug.keystore (local Android SDK default)
                    val projectDebugKs = file("${rootProject.projectDir}/debug.keystore")
                    val homeDebugKs = file("${System.getProperty("user.home")}/.android/debug.keystore")
                    val fallbackKs = if (projectDebugKs.exists()) projectDebugKs else homeDebugKs
                    storeFile = fallbackKs
                    storePassword = "android"
                    keyAlias = "androiddebugkey"
                    keyPassword = "android"
                }
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    // ============================================================
    // Product Flavors — APK size management
    // ============================================================
    // The LLM model (Qwen3.5-0.8B Q4_K_M) is ~580MB. Bundling it
    // creates a 700MB+ APK, exceeding Google Play's 150MB limit.
    //
    // Flavor strategy:
    //   full — bundles ALL models (voice + LLM) for direct APK distribution
    //   lite — bundles only voice models; LLM downloads on first launch
    //          Suitable for Google Play (APK stays under 150MB)
    //   play — bundles only voice models; LLM via Play Asset Delivery
    //          Best Play Store experience (no first-launch download wait)
    // ============================================================
    flavorDimensions += "distribution"
    productFlavors {
        create("full") {
            dimension = "distribution"
            // Bundles all models: voice + LLM GGUF (~650MB total APK)
            // For direct APK distribution (sideloading, internal testing)
            buildConfigField("boolean", "BUNDLE_LLM_MODEL", "true")
            buildConfigField("boolean", "USE_PLAY_ASSET_DELIVERY", "false")
        }
        create("lite") {
            dimension = "distribution"
            // Bundles only voice models (~65MB total APK)
            // LLM downloads on first launch via ModelDownloader
            // Suitable for Google Play Store
            buildConfigField("boolean", "BUNDLE_LLM_MODEL", "false")
            buildConfigField("boolean", "USE_PLAY_ASSET_DELIVERY", "false")
        }
        create("play") {
            dimension = "distribution"
            // Same as lite but uses Play Asset Delivery for LLM
            // Large models served by Google Play, not bundled in APK
            buildConfigField("boolean", "BUNDLE_LLM_MODEL", "false")
            buildConfigField("boolean", "USE_PLAY_ASSET_DELIVERY", "true")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += listOf(
            "-opt-in=kotlin.RequiresOptIn",
            "-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"
        )
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/versions/9/OSGI-INF/MANIFEST.MF"
            excludes += "/META-INF/versions/17/OSGI-INF/MANIFEST.MF"
        }
        jniLibs {
            useLegacyPackaging = true
        }
    }

    // Return default values for android.util.Log etc. in unit tests
    // Required because source code uses Timber (which wraps android.util.Log)
    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    // Don't compress large model files — they need to be memory-mapped or streamed
    // GGUF (~580MB) and ONNX (~40-80MB) models must remain uncompressed for mmap access
    androidResources {
        noCompress += listOf("gguf", "onnx", "bin", "tokens", "fst")
    }
}

dependencies {
    // Core Android
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.fragment:fragment-ktx:1.6.2")

    // Lifecycle (ViewModel, LiveData)
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-process:2.8.7")

    // Navigation
    implementation("androidx.navigation:navigation-fragment-ktx:2.7.6")
    implementation("androidx.navigation:navigation-ui-ktx:2.7.6")

    // Room Database — KSP replaces kapt for annotation processing
    // 2.6.1: Stable release, Kotlin 2.0 KSP support, production-ready
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    implementation("androidx.room:room-paging:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")  // was: kapt(...)

    // SQLCipher for Room database encryption
    implementation("net.zetetic:android-database-sqlcipher:4.5.4")
    implementation("androidx.sqlite:sqlite:2.4.0")

    // Hilt DI — KSP replaces kapt
    // 2.52: Kotlin 2.0 KSP support, improved incremental processing
    implementation("com.google.dagger:hilt-android:2.52")
    ksp("com.google.dagger:hilt-android-compiler:2.52")  // was: kapt(...)

    // Kotlin reflect — MUST match Kotlin compiler 2.0.21
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.0.21")

    // Coroutines — 1.9.0: improved structured concurrency, better debugging
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // Kotlin Serialization (for JSON)
    // 1.7.3: Kotlin 2.0+ support, improved performance
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

    // Retrofit + Gson
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.google.code.gson:gson:2.10.1")

    // Network (Ktor client for sync)
    // Ktor 3.0.3: Requires Kotlin 2.0+ (transitively pulls kotlinx-serialization 1.7.x)
    implementation("io.ktor:ktor-client-core:3.0.3")
    implementation("io.ktor:ktor-client-okhttp:3.0.3")
    implementation("io.ktor:ktor-client-content-negotiation:3.0.3")
    implementation("io.ktor:ktor-serialization-kotlinx-json:3.0.3")
    implementation("io.ktor:ktor-client-logging:3.0.3")

    // DataStore (preferences)
    implementation("androidx.datastore:datastore-preferences:1.0.0")

    // EncryptedSharedPreferences
    implementation("androidx.security:security-crypto:1.1.0-alpha06")

    // WorkManager — 2.10.0: improved battery-aware scheduling
    implementation("androidx.work:work-runtime-ktx:2.10.0")
    implementation("androidx.hilt:hilt-work:1.2.0")
    ksp("androidx.hilt:hilt-compiler:1.2.0")  // was: kapt(...)

    // zstd compression for sync
    implementation("com.github.luben:zstd-jni:1.5.5-11@aar")

    // ONNX Runtime — 1.20.0: ARM inference optimization, NNAPI improvements
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.20.0")

    // Sherpa-ONNX — gold-standard offline voice (ASR/TTS/VAD) for Android
    // JNI libs (libsherpa-onnx-jni.so + libonnxruntime.so) are downloaded via
    // scripts/setup-sherpa-onnx.sh and placed in app/src/main/jniLibs/arm64-v8a/
    // The Kotlin API source files live in app/src/main/java/com/k2fsa/sherpa/onnx/

    // Lottie for animations
    implementation("com.airbnb.android:lottie:6.3.0")

    // Timber logging
    implementation("com.jakewharton.timber:timber:5.0.1")

    // SwipeRefreshLayout
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")

    // Biometric authentication
    implementation("androidx.biometric:biometric:1.1.0")

    // CameraX — receipt scanning
    val cameraxVersion = "1.4.1"
    implementation("androidx.camera:camera-core:$cameraxVersion")
    implementation("androidx.camera:camera-camera2:$cameraxVersion")
    implementation("androidx.camera:camera-lifecycle:$cameraxVersion")
    implementation("androidx.camera:camera-view:$cameraxVersion")

    // ML Kit Text Recognition — on-device OCR (260KB, handles Latin script = English + Swahili)
    implementation("com.google.mlkit:text-recognition:16.0.1")

    // MPAndroidChart for dashboard
    implementation("com.github.PhilJay:MPAndroidChart:v3.1.0")

    // Testing — Unit (JUnit 5 + MockK + Turbine)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.10.1")
    testImplementation("io.mockk:mockk:1.13.9")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
    testImplementation("app.cash.turbine:turbine:1.0.0")
    // Keep JUnit 4 + vintage engine for backward compat
    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.10.1")

    // Testing — Android Integration
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation("androidx.room:room-testing:2.6.1")
    androidTestImplementation("androidx.test:runner:1.5.2")

    // Detekt linting
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.23.7")

    // Bouncy Castle — Post-Quantum Cryptography (ML-KEM, ML-DSA)
    // bcprov-jdk18on 1.84 includes production FIPS 203 (ML-KEM) and FIPS 204 (ML-DSA)
    implementation("org.bouncycastle:bcprov-jdk18on:1.84")
    implementation("org.bouncycastle:bcpkix-jdk18on:1.84")
    implementation("org.bouncycastle:bctls-jdk18on:1.84")

    // Sentry crash reporting
    implementation("io.sentry:sentry-android:7.22.4")
}

// KSP configuration — Room schema export
// (replaces javaCompileOptions.annotationProcessorOptions for kapt)
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.incremental", "true")
    // room.generateKotlin is a Room 2.7+ feature; not needed for 2.6.1 (generates Java by default)
    arg("room.verbose", "true")
}

// Kotlin 2.0.21 — all deps are now consistent, no force hacks needed.
// Ktor 3.0.3 pulls kotlinx-serialization 1.7.x natively.
// Room 2.6.1 (stable), Hilt 2.52 all target Kotlin 2.0+.

// sherpa-onnx JNI setup — downloads native libs before build
tasks.register("setupSherpaOnnx", Exec::class.java) {
    workingDir = rootProject.projectDir
    commandLine("bash", "scripts/setup-sherpa-onnx.sh")
}
tasks.named("preBuild") { dependsOn("setupSherpaOnnx") }

// JUnit 5 platform for all test tasks
tasks.withType<Test> {
    useJUnitPlatform()
}

// JaCoCo code coverage reporting
apply(plugin = "jacoco")
tasks.withType<JacocoReport> {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}
// Kotlin 2.0.21 upgrade: 2026-07-16
// Model config update: Decision Council 2026-07-15
// Build system modernized: removed force hacks, Java 17 target
