package com.msaidizi.app.core.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Inventory item entity.
 * Tracks stock levels, costs, and restocking patterns.
 */
@Entity(tableName = "inventory")
@Serializable
data class InventoryItem(
    @PrimaryKey
    val item: String,

    /** Category (e.g., "produce", "grains", "dairy") */
    val category: String = "",

    /** Current stock quantity */
    val currentStock: Double = 0.0,

    /** Unit of measurement (pieces, kg, liters) */
    val unit: String = "pieces",

    /** Rolling average cost per unit in KSh */
    val avgCost: Double = 0.0,

    /** Alert when stock falls below this */
    val restockThreshold: Double = 5.0,

    /** Typical restock quantity */
    val restockQuantity: Double = 0.0,

    /** Last restock timestamp (Unix seconds) */
    val lastRestockedAt: Long? = null,

    /** Predicted restock interval in milliseconds */
    val predictedIntervalMs: Long = 0,

    /** Predicted restock quantity based on patterns */
    val predictedQuantity: Double = 0.0,

    /** Last update timestamp */
    val updatedAt: Long = System.currentTimeMillis() / 1000
)

/**
 * Restock alert generated by the BusinessAgent.
 */
data class RestockAlert(
    val item: String,
    val currentStock: Double,
    val threshold: Double,
    val avgCost: Double,
    val daysUntilStockout: Int = -1
)
