#!/usr/bin/env python3
"""
kapt Compatibility Checker for Msaidizi App.

Prevents the `Could not load module <Error module>` build failure by checking:
1. @Serializable is NOT on Room @Entity classes (causes kapt conflict)
2. No duplicate class names in the same package
3. All imports resolve to existing files

Exit code 0 = all checks passed.
Exit code 1 = one or more issues found.
"""
import os
import re
import sys
from collections import defaultdict

SRC_ROOT = "app/src/main/java"

# Auto-generated by Android build system — not in source tree
GENERATED_CLASSES = {
    'com.msaidizi.app.R',
    'com.msaidizi.app.BuildConfig',
}

# Packages that contain auto-generated code
GENERATED_PACKAGE_PREFIXES = [
    'com.msaidizi.app.databinding',
    'com.msaidizi.appBR',  # DataBinding BR class
]


def find_package_and_classes(filepath: str) -> tuple[str, list[tuple[str, int]]]:
    """Extract package name and all top-level class declarations from a file."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except (OSError, UnicodeDecodeError):
        return ("", [])

    package = ""
    classes = []
    depth = 0
    in_block_comment = False

    for i, line in enumerate(lines):
        stripped = line.strip()

        if in_block_comment:
            if '*/' in stripped:
                in_block_comment = False
            continue
        if '/*' in stripped and '*/' not in stripped:
            in_block_comment = True
            continue
        if stripped.startswith('//'):
            continue

        pkg_match = re.match(r'^package\s+([\w.]+)', stripped)
        if pkg_match:
            package = pkg_match.group(1)

        if depth == 0:
            cls_match = re.match(
                r'^(?:public\s+|private\s+|protected\s+|internal\s+|abstract\s+|open\s+|sealed\s+|data\s+|enum\s+|annotation\s+|inline\s+|value\s+)*'
                r'(?:class|interface|object|enum\s+class)\s+([A-Za-z_]\w*)',
                stripped
            )
            if cls_match:
                classes.append((cls_match.group(1), i + 1))

        for ch in stripped:
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth = max(0, depth - 1)

    return (package, classes)


def check_serializable_on_entity(filepath: str) -> list[tuple[int, str]]:
    """
    Check if any @Entity class in this file also has @Serializable.
    Returns list of (line_number, class_name) for violations.
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except (OSError, UnicodeDecodeError):
        return []

    violations = []
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if re.match(r'@Entity\b', stripped):
            annotations = [stripped]
            j = i + 1
            class_name = None
            while j < min(i + 20, len(lines)):
                s = lines[j].strip()
                annotations.append(s)
                m = re.match(
                    r'(?:data\s+|enum\s+|sealed\s+|abstract\s+|open\s+)?class\s+([A-Za-z_]\w*)',
                    s
                )
                if m:
                    class_name = m.group(1)
                    break
                if s and not s.startswith('@') and not s.startswith('(') and not s.startswith(')') and not s.startswith('data') and not s.startswith('enum'):
                    break
                j += 1
            if class_name:
                all_annots = ' '.join(annotations)
                if '@Serializable' in all_annots:
                    violations.append((i + 1, class_name))
            i = j + 1 if class_name else i + 1
        else:
            i += 1
    return violations


def check_duplicate_classes(src_root: str) -> dict[str, list[str]]:
    """Find duplicate class names within the same package."""
    class_map: dict[tuple[str, str], list[str]] = defaultdict(list)
    for dirpath, _, filenames in os.walk(src_root):
        for fname in filenames:
            if not fname.endswith('.kt'):
                continue
            fpath = os.path.join(dirpath, fname)
            package, classes = find_package_and_classes(fpath)
            for class_name, _ in classes:
                class_map[(package, class_name)].append(fpath)
    duplicates = {}
    for (pkg, name), paths in class_map.items():
        if len(paths) > 1:
            qualified = f"{pkg}.{name}" if pkg else name
            duplicates[qualified] = paths
    return duplicates


def check_imports_resolve(src_root: str) -> list[tuple[str, int, str]]:
    """
    Check that all `import com.msaidizi.app.*` statements resolve.
    Resolves by: file path match OR class name in the target package.
    Skips auto-generated classes (R, BuildConfig, databinding/*).
    """
    # Build: package -> set of class names available in that package
    package_classes: dict[str, set[str]] = defaultdict(set)
    existing_packages: set[str] = set()

    for dirpath, _, filenames in os.walk(src_root):
        for fname in filenames:
            if not fname.endswith('.kt'):
                continue
            fpath = os.path.join(dirpath, fname)
            package, classes = find_package_and_classes(fpath)
            if package:
                existing_packages.add(package)
                for class_name, _ in classes:
                    package_classes[package].add(class_name)

    # Also add directory-based packages (for wildcard import targets)
    for dirpath, dirnames, _ in os.walk(src_root):
        rel = os.path.relpath(dirpath, src_root)
        if rel == '.':
            continue
        pkg = rel.replace(os.sep, '.')
        existing_packages.add(pkg)

    unresolvable = []
    # Match both specific imports and wildcard imports
    import_pattern = re.compile(r'^import\s+(com\.msaidizi\.app[\w.*]*)')

    for dirpath, _, filenames in os.walk(src_root):
        for fname in filenames:
            if not fname.endswith('.kt'):
                continue
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, 'r', encoding='utf-8') as f:
                    for line_num, line in enumerate(f, 1):
                        m = import_pattern.match(line.strip())
                        if not m:
                            continue
                        import_path = m.group(1)

                        # Skip auto-generated classes
                        if import_path in GENERATED_CLASSES:
                            continue
                        if any(import_path.startswith(p) for p in GENERATED_PACKAGE_PREFIXES):
                            continue

                        if import_path.endswith('.*'):
                            # Wildcard import: check if package exists
                            pkg = import_path[:-2]
                            if pkg in existing_packages:
                                continue
                            # Check if any sub-package exists
                            if any(p.startswith(pkg + '.') for p in existing_packages):
                                continue
                            unresolvable.append((fpath, line_num, import_path))
                        elif import_path.endswith('.'):
                            # Trailing dot without wildcard — malformed, skip
                            continue
                        else:
                            # Specific import: e.g. com.msaidizi.app.core.model.CashFlow
                            parts = import_path.rsplit('.', 1)
                            if len(parts) != 2:
                                continue
                            pkg, cls = parts

                            # Method 1: File at expected path exists
                            file_path = os.path.join(src_root, import_path.replace('.', os.sep) + '.kt')
                            if os.path.exists(file_path):
                                continue

                            # Method 2: Class declared in the package
                            if cls in package_classes.get(pkg, set()):
                                continue

                            # Method 3: Check parent packages (for nested qualified names)
                            resolved = False
                            for existing_pkg in sorted(existing_packages, key=len, reverse=True):
                                if import_path.startswith(existing_pkg + '.'):
                                    remainder = import_path[len(existing_pkg) + 1:]
                                    if '.' not in remainder and remainder in package_classes.get(existing_pkg, set()):
                                        resolved = True
                                        break

                            if not resolved:
                                unresolvable.append((fpath, line_num, import_path))
            except (OSError, UnicodeDecodeError):
                continue

    return unresolvable


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(repo_root)

    print("🔍 kapt Compatibility Checker")
    print("=" * 40)
    total_errors = 0

    # ── Check 1: @Serializable on @Entity ──
    print("\n📋 Check 1: @Serializable on @Entity classes...")
    serializable_violations = []
    for dirpath, _, filenames in os.walk(SRC_ROOT):
        for fname in filenames:
            if not fname.endswith('.kt'):
                continue
            fpath = os.path.join(dirpath, fname)
            violations = check_serializable_on_entity(fpath)
            for line_num, class_name in violations:
                serializable_violations.append((fpath, line_num, class_name))

    if serializable_violations:
        for fpath, line, cls in serializable_violations:
            print(f"  ❌ @Serializable on @Entity class '{cls}' at {fpath}:{line}")
        total_errors += len(serializable_violations)
    else:
        print("  ✅ No @Serializable on @Entity classes")

    # ── Check 2: Duplicate class names in same package ──
    print("\n📋 Check 2: Duplicate class names in same package...")
    duplicates = check_duplicate_classes(SRC_ROOT)
    if duplicates:
        for qualified, paths in sorted(duplicates.items()):
            print(f"  ❌ Duplicate class '{qualified}':")
            for p in paths:
                print(f"      → {p}")
        total_errors += len(duplicates)
    else:
        print("  ✅ No duplicate class names in same package")

    # ── Check 3: Import resolution ──
    print("\n📋 Check 3: Unresolvable imports...")
    bad_imports = check_imports_resolve(SRC_ROOT)
    if bad_imports:
        for fpath, line_num, import_path in bad_imports[:50]:
            print(f"  ❌ {fpath}:{line_num}  →  import {import_path}")
        if len(bad_imports) > 50:
            print(f"  ... and {len(bad_imports) - 50} more")
        total_errors += len(bad_imports)
    else:
        print("  ✅ All imports resolve")

    # ── Summary ──
    print("\n" + "=" * 40)
    if total_errors > 0:
        print(f"❌ FOUND {total_errors} ISSUE(S) — kapt will likely fail")
        print("   Fix these before committing to avoid 'Could not load module' errors")
        sys.exit(1)
    else:
        print("✅ ALL KAPT COMPATIBILITY CHECKS PASSED")
        sys.exit(0)


if __name__ == '__main__':
    main()
